import { defineConfig } from 'vitest/config';
import { resolve } from 'node:path';

const TEST_ENV: Record<string, string> = {
  NODE_ENV: 'test',
  LOG_LEVEL: 'error',
  APP_NAME: 'engageiq-api-test',
  APP_VERSION: '0.0.0-test',
  HOST: '127.0.0.1',
  PORT: '0',
  TRUST_PROXY: 'true',
  APP_PUBLIC_URL: 'http://localhost:3000',
  API_PUBLIC_URL: 'http://localhost:4000',
  CORS_ORIGINS: 'http://localhost:3000',
  DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/engageiq_test',
  REDIS_URL: 'redis://localhost:6379/15',
  NATS_URL: 'nats://localhost:4222',
  JWT_ACCESS_SECRET: 'test-access-secret-with-at-least-32-characters-long',
  JWT_REFRESH_SECRET: 'test-refresh-secret-with-at-least-32-characters-long',
  JWT_ACCESS_TTL: '15m',
  JWT_REFRESH_TTL: '30d',
  BCRYPT_ROUNDS: '4',
  ACCOUNT_LOCKOUT_MAX_ATTEMPTS: '3',
  ACCOUNT_LOCKOUT_DURATION_S: '60',
  PASSWORD_RESET_TTL_S: '3600',
  EMAIL_VERIFICATION_TTL_S: '86400',
  INVITE_TTL_S: '604800',
  INTERNAL_API_KEY: 'test-internal-key-do-not-use',
  EMAIL_FROM: 'test@engageiq.test',
  AWS_REGION: 'us-east-1',
  SWAGGER_ENABLED: 'false',
  STRIPE_SECRET_KEY: 'sk_test_dummy_for_unit_tests',
  STRIPE_WEBHOOK_SECRET: 'whsec_test_dummy',
  STRIPE_CHECKOUT_SUCCESS_URL: 'http://localhost:3000/billing/success',
  STRIPE_CHECKOUT_CANCEL_URL: 'http://localhost:3000/billing/cancel',
  STRIPE_PORTAL_RETURN_URL: 'http://localhost:3000/billing',
  STRIPE_STARTER_MONTHLY_PRICE_ID: 'price_test_starter_monthly',
  STRIPE_STARTER_YEARLY_PRICE_ID: 'price_test_starter_yearly',
  STRIPE_GROWTH_MONTHLY_PRICE_ID: 'price_test_growth_monthly',
  STRIPE_GROWTH_YEARLY_PRICE_ID: 'price_test_growth_yearly',
  STRIPE_PRO_MONTHLY_PRICE_ID: 'price_test_pro_monthly',
  STRIPE_PRO_YEARLY_PRICE_ID: 'price_test_pro_yearly',
};

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    env: TEST_ENV,
    include: ['test/unit/**/*.test.ts', 'test/integration/**/*.test.ts'],
    exclude: ['node_modules', 'dist', 'test/e2e/**'],
    setupFiles: ['test/setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov', 'html'],
      include: ['src/**/*.ts'],
      exclude: [
        'src/**/*.d.ts',
        'src/app/server.ts',
        'src/observability/**',
        'src/**/index.ts',
      ],
      thresholds: {
        lines: 70,
        functions: 70,
        statements: 70,
        branches: 60,
      },
    },
    testTimeout: 30000,
    hookTimeout: 30000,
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
      '@app': resolve(__dirname, 'src/app'),
      '@config': resolve(__dirname, 'src/config'),
      '@constants': resolve(__dirname, 'src/constants'),
      '@http': resolve(__dirname, 'src/http'),
      '@modules': resolve(__dirname, 'src/modules'),
      '@plugins': resolve(__dirname, 'src/plugins'),
      '@shared': resolve(__dirname, 'src/shared'),
      '@observability': resolve(__dirname, 'src/observability'),
      '@test': resolve(__dirname, 'test'),
    },
  },
});
