/**
 * Standalone migration runner. Run via `npm run db:migrate`.
 *
 * Reads SQL migrations from ./database/migrations (generated by drizzle-kit).
 */
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import { createDb } from '../src/shared/database/client.js';

async function main(): Promise<void> {
  const { db, client } = createDb();
  try {
    // eslint-disable-next-line no-console
    console.log('[migrate] Running migrations...');
    await migrate(db, { migrationsFolder: './database/migrations' });
    // eslint-disable-next-line no-console
    console.log('[migrate] Migrations complete.');
  } finally {
    await client.end({ timeout: 5 });
  }
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error('[migrate] Failed:', err);
  process.exit(1);
});
